<select id = "cities">
<option value = "Amsterdam">Amsterdam</option>
<option value = "Ankara">Ankara</option>
<option value = "Athens">Athens</option>
<option value = "Atlantic City">Atlantic City</option>
<option value = "Baltimore">Baltimore</option>
<option value = "Bangkok">Bangkok</option>
<option value = "Beijing">Beijing</option>
<option value = "Berlin">Berlin</option>
<option value = "Berne">Berne</option>
<option value = "Brussels">Brussels</option>
<option value = "Budapest">Budapest</option>
<option value = "Buenos Aires">Buenos Aires</option>
<option value = "Cairo">Cairo</option>
<option value = "Canberra">Canberra</option> 
<option value = "Cannes">Cannes</option> 
<option value = "Cape Town">Cape Town</option>
<option value = "Chicago">Chicago</option>
<option value = "Cologne">Cologne</option>
<option value = "Copenhagen">Copenhagen</option>
<option value = "Damascus">Damascus</option>
<option value = "Delhi">Delhi</option>
<option value = "Dubai City">Dubai City</option>
<option value = "Dublin">Dublin</option>
<option value = "Florence">Florence</option>
<option value = "Geneva">Geneva</option>
<option value = "Hague">Hague</option>
<option value = "Ha Noi">Ha Noi</option>
<option value = "Havana">Havana</option>
<option value = "Helsinki">Helsinki</option>
<option value = "Hong Kong">Hong Kong</option>
<option value = "Honolulu">Honolulu</option>
<option value = "Istanbul">Istanbul</option> 
<option value = "Jakarta">Jakarta</option>
<option value = "Jerusalem">Jerusalem</option>
<option value = "Kansas City">Kansas City</option>
<option value = "Kathmandu">Kathmandu</option>
<option value = "Kuala Lumpur">Kuala Lumpur</option>
<option value = "Lisbon">Lisbon</option>
<option value = "London">London</option>
<option value = "Los Angeles">Los Angeles</option>
<option value = "Luxembourg">Luxembourg</option>
<option value = "Madrid">Madrid</option>
<option value = "Manila">Manila</option>
<option value = "Melbourne">Melbourne</option>
<option value = "Mexico">Mexico</option>
<option value = "Milan">Milan</option>
<option value = "Montreal">Montreal</option>
<option value = "Moscow">Moscow</option>
<option value = "Mumbai">Mumbai</option>
<option value = "Munich">Munich</option>
<option value = "Nazareth">Nazareth</option>
<option value = "New York">New York</option>
<option value = "Nice">Nice</option>
<option value = "Osaka">Osaka</option>
<option value = "Ottawa">Ottawa</option>
<option value = "Oslo">Oslo</option>
<option value = "Paris">Paris</option>
<option value = "Philadelphia">Philadelphia</option>
<option value = "Phnom Penh">Phnom Penh</option>
<option value = "Prague">Prague</option>
<option value = "Quito">Quito</option>
<option value = "Reykjavik">Reykjavik</option>
<option value = "Rio de Janeiro">Rio de Janeiro</option>
<option value = "San Francisco">San Francisco</option>
<option value = "Santa Fe">Santa Fe</option>
<option value = "Santiago">Santiago</option>
<option value = "Sao Paulo">Sao Paulo</option>
<option value = "Shanghai">Shanghai</option>
<option value = "Singapore">Singapore</option>
<option value = "Stockholm">Stockholm</option>
<option value = "Saint-Petersburg">Saint-Petersburg</option>
<option value = "Sydney">Sydney</option>
<option value = "Taipei">Taipei</option>
<option value = "Tokyo">Tokyo</option>
<option value = "Toronto">Toronto</option>
<option value = "Venice">Venice</option>
<option value = "Vienna">Vienna</option>
<option value = "Washington">Washington</option>
<option value = "Zurich">Zurich</option>
</select>